version: '3.8'

services:
  uaa-db:
    image: postgres
    container_name: uaa-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  uaa:
    image: cloudfoundry/uaa:76.0.0
    container_name: uaa
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./uaa.yml:/uaa/uaa.yml

  localstack:
    container_name: localstack
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
